In [1]:
import pandas as pd

In [54]:
df=pd.read_csv('http://bit.ly/imdbratings')

In [55]:
df.dtypes

star_rating       float64
title              object
content_rating     object
genre              object
duration            int64
actors_list        object
dtype: object

In [56]:
df

,star_rating,title,content_rating,genre,duration,actors_list
0,9.3,The Shawshank Redemption,R,Crime,142,"[u'Tim Robbins', u'Morgan Freeman', u'Bob Gunt..."
1,9.2,The Godfather,R,Crime,175,"[u'Marlon Brando', u'Al Pacino', u'James Caan']"
2,9.1,The Godfather: Part II,R,Crime,200,"[u'Al Pacino', u'Robert De Niro', u'Robert Duv..."
3,9.0,The Dark Knight,PG-13,Action,152,"[u'Christian Bale', u'Heath Ledger', u'Aaron E..."
4,8.9,Pulp Fiction,R,Crime,154,"[u'John Travolta', u'Uma Thurman', u'Samuel L...."
...,...,...,...,...,...,...
974,7.4,Tootsie,PG,Comedy,116,"[u'Dustin Hoffman', u'Jessica Lange', u'Teri G..."
975,7.4,Back to the Future Part III,PG,Adventure,118,"[u'Michael J. Fox', u'Christopher Lloyd', u'Ma..."
976,7.4,Master and Commander: The Far Side of the World,PG-13,Action,138,"[u'Russell Crowe', u'Paul Bettany', u'Billy Bo..."
977,7.4,Poltergeist,PG,Horror,114,"[u'JoBeth Williams', u""Heather O'Rourke"", u'Cr..."
978,7.4,Wall Street,R,Crime,126,"[u'Charlie Sheen', u'Michael Douglas', u'Tamar..."

In [61]:
df.groupby('genre').agg(['mean','median','min','max','count'])

          star_rating                           duration                   \
                 mean median  min  max count        mean median  min  max
genre
Action       7.884559   7.80  7.4  9.0   136  126.485294  125.0   80  205
Adventure    7.933333   7.90  7.4  8.9    75  134.840000  127.0   89  224
Animation    7.914516   7.90  7.4  8.6    62   96.596774   94.5   75  134
Biography    7.862338   7.80  7.4  8.9    77  131.844156  127.0   85  202
Comedy       7.822436   7.80  7.4  8.6   156  107.602564  104.0   68  187
Crime        7.916935   7.80  7.4  9.3   124  122.298387  118.0   67  229
Drama        7.902518   7.90  7.4  8.9   278  126.539568  123.0   64  242
Family       7.850000   7.85  7.8  7.9     2  107.500000  107.5  100  115
Fantasy      7.700000   7.70  7.7  7.7     1  112.000000  112.0  112  112
Film-Noir    8.033333   8.10  7.7  8.3     3   97.333333   93.0   88  111
History      8.000000   8.00  8.0  8.0     1   66.000000   66.0   66   66
Horror       7.806897   7.70  7.4  8.6    29  102.517241  104.0   70  146
Mystery      7.975000   8.10  7.4  8.6    16  115.625000  115.0   69  160
Sci-Fi       7.920000   7.90  7.7  8.2     5  109.000000  113.0   91  132
Thriller     7.680000   7.60  7.5  8.0     5  114.200000  116.0  107  120
Western      8.255556   8.30  7.6  8.9     9  136.666667  135.0   85  175


          count
genre
Action      136
Adventure    75
Animation    62
Biography    77
Comedy      156
Crime       124
Drama       278
Family        2
Fantasy       1
Film-Noir     3
History       1
Horror       29
Mystery      16
Sci-Fi        5
Thriller      5
Western       9